### ISSUE TITLE
Brainstorming the project ideas and deciding one amongst them.

### ISSUE THREAD

**Issue by TheBloodMage** [tungatkarniranjan/CMP202-Project-Group-5#1]
Brainstorming the project ideas and deciding one amongst them.

**Comment by TheBloodMage** [comment]
Suggested an idea regarding a small game which can be developed using the **Graph Coloring Algorithm.**

In this game, the graph will be designed using tube lights which will light with different colors.
At any time no two adjacent tube lights will have the same color that will light them up.

A simple overview of the rules is as follows,

1. A random graph with tube lights as its sides will be generated.
2. The set of colours will be decided and for each map. Only a certain set of colours will be utilized for the completion of each map.
3. A user will play its first turn and will light one of the many tubes available.
4. The user will have freedom to select any tube light and any color at the start of the game however his choices will be restrained as the game proceeds its lifetime.
5.. Game will be complete only if each side of the random map has a tube light which is active.
6. Each graph will have a correct answer and it will be showed to the user if he asks for it.
7. Points will be decided with the help of time taken to solve the map, steps taken, number of BACK options a user used during solving a map.
8. Use of algorithm will be done while solving the map and checking if the user has solved the map correctly.

This is a crude aspect and will be refined as the time proceeds.

**Comment by ajaytanpure** [comment]
By using the minimal spanning tree algorithm, we can design the game for travelling a car from point A to point B. There will be multiple halts in between the point A and point B which will serve as the  nodes of the graph.  Using the minimum fuel, car should reach the destination.

**Comment by ajaytanpure** [comment]
Added two files Minimal_Spanning_Tree_Game.txt and Minimal_Spanning_Tree_Game_sketch.jpg explaining the idea of the game

**Comment by TheBloodMage** [comment]
Working on a single player game in which we can employ 'Graph Coloring Algorithm' to light different bulbs that are placed at the vertices of a map and no two adjacent bulbs can be light that are of same color. The game completes when you light all the bulbs in the map successfully. The score will be decided upon the time required to complete the map, number of hints used.

**Comment by darshan009** [comment]
With searching algorithm we can develop a game which includes a number of numbered ships ordered according to their numbers, of which a particular numbered ship is to be found. There would be certain hurdles on the way like a decoy ship which when opened explodes and ends game.

**Comment by mtanwar21** [comment]
Studied the Csunplugged Public key encryption and Cryptographic activities. Went through the listed game for each activity, researched the activity to identify its feasible implementation in a multi-player game and scenarios that can be taken, to build a game. Focus is on to come up with a game which is easy to play and easy to understand .

**Comment by raktag** [comment]
Looking into the Information hiding techniques which can be used to create a game where in our algorithm generates a scrambled image or may be a file/message and the user has to guess the image from the hints provided by our algorithm. Also looked through the CS unplugged activity of information hiding to come up with a game on similar lines.
