### ISSUE TITLE
Defining the gaming world (map)

### ISSUE THREAD

**Issue by TheBloodMage** [tungatkarniranjan/CMP202-Project-Group-5#14]
Define a map which will have all the actors such as Enemies, Cities, Ammunition and other such actors that are involved in game lifetime

**Comment by TheBloodMage** [comment]
Collect images to be used as cities and some simple sample basic world images which can be used as our game map. Example: Lord Of the Rings map, Game Of Thrones middle world map, Narnia Map or Jumanji Map etc.

**Comment by TheBloodMage** [comment]
Gathered some sample images for the Game Map and committed on the github.

**Comment by ajaytanpure** [comment]
images looks good

**Comment by ajaytanpure** [comment]
For now we have collected some images. As we create more maps, we will collects more images for rest.

**Comment by TheBloodMage** [comment]
Finalized, tested and reviewed
