### ISSUE TITLE
Define a simple prototype of the cipher technique that I suggested

### ISSUE THREAD

**Issue by TheBloodMage** [tungatkarniranjan/CMP202-Project-Group-5#15]
Define a simple prototype in greenfoot that will implement the main interface of 'Cipher Techniques' and try to code your technique.

**Comment by TheBloodMage** [comment]
Decide to work on the prototype of Vigener Cipher.
Uploaded a document specifying the simple working of the cipher technique.
After that main interface conding is started.

**Comment by TheBloodMage** [comment]
Created a simple prototype sticking to our main interface. Added to review.

**Comment by TheBloodMage** [comment]
extended the class CipherThree from Actor class, made some changes in the code. 
adjusted the string output.
added description placeholder.

**Comment by ajaytanpure** [comment]
Reviewed, looks ok

**Comment by ajaytanpure** [comment]
tested with sample string and checked the encrypted string. Looks fine
