### ISSUE TITLE
implementing the cipher interface in cipher simulation  technique 1

### ISSUE THREAD

**Issue by ajaytanpure** [tungatkarniranjan/CMP202-Project-Group-5#16]

**Comment by ajaytanpure** [comment]
I have created two concrete classes CipherOne.java and CipherTwo.java which implements the cipher interface

**Comment by ajaytanpure** [comment]
Implemented the CipherOne technique. In this technique, string is revered and cases are toggled and every alternate character in the resulting string is changed.
Updated code has been pushed in GitHub

**Comment by raktag** [comment]
Reviewed

**Comment by raktag** [comment]
Tests executed: -
1. Check if string is encrypted
2. Check if string is decrypted and is matched.
Tests passed.
