### ISSUE TITLE
Creating the hints for cipher techniques simulation-1

### ISSUE THREAD

**Issue by ajaytanpure** [tungatkarniranjan/CMP202-Project-Group-5#17]

**Comment by TheBloodMage** [comment]
Collect images to be used as cities and some simple sample basic  world images which can be used as our game map. Example: Lord Of the Rings map, Game Of Thrones middle world map, Narnia Map or Jumanji Map etc.

**Comment by ajaytanpure** [comment]
Creating hints for ciphers on click on help button

**Comment by ajaytanpure** [comment]
this is no longer needed
