### ISSUE TITLE
Selecting the one game and defining the scope and rules for the game

### ISSUE THREAD

**Issue by raktag** [tungatkarniranjan/CMP202-Project-Group-5#2]

**Comment by TheBloodMage** [comment]
Game Name: **Tubelight Tunneling** 
**Rules:**

1.  Select map. Colors will be provided.
2.  Select a tube light to turn on.
3. Restrictions : Can not turn on an adjacent light if they have same colour. All tube lights must be turned on.
4. The score will be decided upon the number of attempts, total number of BACK buttons used, total number of hints used and total amount of time required.
5. Option will be given to submit and solve the map by the computer as answer.

This is just a crude module and the idea and rules will get refined over the time.

**Comment by mtanwar21** [comment]
We can implement the cryptography protocols in a game replicating the stressing events of world war 2, the enigma machine send code to Nazi’s warheads to instruct which city to attack. And Allies have to decode the code to prevent the attack and win the war.
Our game will display the cryptic message of Nazis which contains information of which city will be attacked. User have to decrypt the message using the puzzle board.

 Europe map will be our greentfoot world having different cities of allies in Europe as city actor, Actor tanks will rotate around the cities to attack them. Tanks will get an encrypted city name message to attack a city.  The encrypted message will be displayed to the user in the puzzle display board. The user than try to decrypt the message to find the city name and build a wall in front of city to prevent it, or arrange arsenal for that city. So user will run against the time for attack and he can opt for hint with deduction on his starting point or can guess and build a wall or arrange arsenal against the city on cost of his points. if his guess works his points will be added 5 points. And if user cracked the code his points will be added with 10 points. 

User who runs out of his points will lose the match.

A cryptography wheel will be at the user disposal to help solve the puzzle.

We can include various techniques to encrypt the message which can be used in different rounds and at different difficulty levels.
The game rules, actors and scope have to be discussed further  and idea can be  refined and build around the same concept.

**Comment by ajaytanpure** [comment]
Game has been discussed in details. Started with implementing the prototype
