### ISSUE TITLE
Create a RandomUtility actor.

### ISSUE THREAD

**Issue by raktag** [tungatkarniranjan/CMP202-Project-Group-5#30]
This task will contain all the random algorithms that are required for selecting MapScreen, ciphers and city locations

**Comment by raktag** [comment]
Random utility for maps completed.
Task in development to track further modifications and developments to this task

**Comment by ajaytanpure** [comment]
Reviewed, Looks ok

**Comment by ajaytanpure** [comment]
Tested looks ok
