### ISSUE TITLE
Create MapScreen class

### ISSUE THREAD

**Issue by ajaytanpure** [tungatkarniranjan/CMP202-Project-Group-5#32]
Create Mapscreen class. This class will be extended by various classes as FranceMapScreen, GermanyMapScreen and other maps screen that are part of the Game.

**Comment by ajaytanpure** [comment]
Created MapScreen class. Also created FranceMapScreen and GermanyMapScreen class which has images specific those countries. They also loads City objects and displays the city images on the map

**Comment by TheBloodMage** [comment]
verified
