### ISSUE TITLE
Setting up project environment

### ISSUE THREAD

**Issue by raktag** [tungatkarniranjan/CMP202-Project-Group-5#4]
Includes setting up of git repository, task board, google CFD sheet, software installations.

**Comment by ajaytanpure** [comment]
Installed latest java jdk and greenfoot tool, cloned git repository.

**Comment by raktag** [comment]
java jdk 1.8, greenfoot installed. Git Repo cloned.

**Comment by mtanwar21** [comment]
Done with the Installation of  the java JDK and other software requirements

**Comment by TheBloodMage** [comment]
installed java, netbeans, greenfoot, git desktop and other environment setup has been done

**Comment by darshan009** [comment]
installed java, greenfoot, git environment setup and other additions done
